trigger: none
resources:
  repositories:
    - repository: DevOpsTemplates
      name: DigitalPayments/DevOps-Templates
      type: git
      ref: master
  jobs:
    - template: pipelines/restapi1.0-java-sdk.yaml@DevOpsTemplates